services:
  # Spring Boot 应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: production-mgmt:latest
    container_name: product-mgmt
    ports:
      - "8040:8040"
    volumes:
      - /data/product-mgmt/logs:/var/log/product_mgmt
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend

networks:
  backend:
    external: true

