server:
  port: 8040

service:
  ip: ENC(SGOqglPaE1dUyjjA3EEyyMAtiw8oeIhu)

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://${service.ip}:3306/product_mgmt?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    password: ENC(pfnBfUXIfcKWjiNJQNgJ29lEYfQ2AZ5w)
    username: ENC(AkL48Oi3cR5nLEjZJ3Y32Q==)
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      idle-timeout: 60000
      connection-timeout: 60000
      validation-timeout: 3000
      login-timeout: 5
      max-lifetime: 60000
  redis:
    port: 6379
    host: ${service.ip}
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-wait: -1
        max-active: 8
        max-idle: 8
        min-idle: 0
    password: ENC(pfnBfUXIfcKWjiNJQNgJ29lEYfQ2AZ5w)

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
    use-generated-keys: true

#分页设置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

app:
  id: wx2830175c9fa7e38e
  secret: 38d3fa244261c51f7009192fbb4809d8
logging:
  file:
    path: /root/logs/product_mgmt_log
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr([%X{traceId}]) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } [%X{traceId}] --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
#  level:
#    com:
#      chuncongcong:
#        productmgmt:
#          dao: debug

request:
  log:
    enable: false
jasypt:
  encryptor:
    password: 123456
